In [5]:
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from core.data import load_from_kaggle

In [9]:
dataset_link = "oles04/bundesliga-seasons" # replace with your dataset link from Kaggle 
destination = os.path.join('..', 'data','buli_05_to_23', 'raw')


dataset_name = dataset_link.split("/")[-1]

file = load_from_kaggle(
    dataset_link=dataset_link, 
    destination=destination,
    )

Destination directory '..\data\buli_05_to_23\raw\bundesliga-seasons' already exists with files. Skipping download (replace=False).

In [20]:
file
filename = file[0]

In [23]:
file
dataset_folder = os.path.join(destination, dataset_name)

csv_path = os.path.join(dataset_folder,filename)

In [26]:
df = pd.read_csv(csv_path)
df.head()

,Unnamed: 0,MATCH_DATE,LEAGUE_NAME,SEASON,LEAGUE,FINISHED,LOCATION,VIEWER,MATCHDAY,MATCHDAY_NR,...,HOME_ICON,AWAY_TEAM_ID,AWAY_TEAM_NAME,AWAY_TEAM,AWAY_ICON,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
0,0,2005-08-05 20:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,München,NaN,1. Spieltag,1,...,https://i.imgur.com/jJEsJrj.png,87,Borussia Mönchengladbach,Gladbach,https://i.imgur.com/KSIk0Eu.png,3,0,0.0,1.0,0.0
1,1,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Köln,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/en/thum...,81,1. FSV Mainz 05,Mainz,https://upload.wikimedia.org/wikipedia/commons...,1,0,0.0,1.0,0.0
2,2,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Duisburg,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/en/c/c8...,16,VfB Stuttgart,Stuttgart,https://i.imgur.com/v0tkpNx.png,1,1,1.0,0.0,0.0
3,3,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Hamburg,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/commons...,79,1. FC Nürnberg,Nürnberg,https://upload.wikimedia.org/wikipedia/commons...,3,0,0.0,1.0,0.0
4,4,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Wolfsburg,NaN,1. Spieltag,1,...,https://i.imgur.com/ucqKV4B.png,7,Borussia Dortmund,BVB,https://upload.wikimedia.org/wikipedia/commons...,2,2,1.0,0.0,0.0

## eda

In [27]:
display(
    "Shape",
    df.shape,
    "Description",
    df.describe().round(2).T,
    "Duplicates",
    df.duplicated().sum(),
)


pd.DataFrame(
    {
        "Data Types": df.dtypes,
        "Missing Values": df.isnull().sum(),
        "Unique Values": df.nunique(),
        "Sample Values": [df[col].sample(3).tolist() for col in df.columns]
    })

'Shape'

(5508, 23)

'Description'

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,5508.0,2755.06,1590.77,0.0,1378.75,2755.5,4132.25,5509.0
SEASON,5508.0,2013.50,5.19,2005.0,2009.00,2013.5,2018.00,2022.0
VIEWER,1682.0,41841.02,18057.42,0.0,28176.25,41000.0,52121.00,81365.0
MATCHDAY_NR,5508.0,17.50,9.81,1.0,9.00,17.5,26.00,34.0
HOME_TEAM_ID,5508.0,109.76,231.49,6.0,40.00,81.0,112.00,1635.0
AWAY_TEAM_ID,5508.0,109.76,231.49,6.0,40.00,81.0,112.00,1635.0
GOALS_HOME,5508.0,1.39,1.30,0.0,0.00,1.0,2.00,9.0
GOALS_AWAY,5508.0,1.08,1.13,0.0,0.00,1.0,2.00,8.0
DRAW,5508.0,0.29,0.45,0.0,0.00,0.0,1.00,1.0
WIN_HOME,5508.0,0.43,0.49,0.0,0.00,0.0,1.00,1.0
WIN_AWAY,5508.0,0.28,0.45,0.0,0.00,0.0,1.00,1.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
Unnamed: 0,int64,0,5508,"[3695, 4646, 3385]"
MATCH_DATE,object,0,2603,"[2021-10-03 19:30:00, 2009-05-16 15:30:00, 202..."
LEAGUE_NAME,object,0,18,"[1. Fussball-Bundesliga 2012/2013, 1. Fussball..."
SEASON,int64,0,18,"[2019, 2009, 2015]"
LEAGUE,object,0,1,"[bl1, bl1, bl1]"
FINISHED,bool,0,1,"[True, True, True]"
LOCATION,object,0,33,"[Stuttgart, Dortmund, Leipzig]"
VIEWER,float64,3826,814,"[nan, nan, 53000.0]"
MATCHDAY,object,0,34,"[25. Spieltag, 1. Spieltag, 26. Spieltag]"
MATCHDAY_NR,int64,0,34,"[13, 33, 28]"
HOME_TEAM_ID,int64,0,36,"[91, 9, 100]"
HOME_TEAM_NAME,object,0,35,"[Bayer Leverkusen, Fortuna Düsseldorf, TSG 189..."
HOME_TEAM,object,0,35,"[Hoffenheim, Bremen, Frankfurt]"
HOME_ICON,object,0,37,[https://assets.dfb.de/uploads/000/018/232/sma...
AWAY_TEAM_ID,int64,0,36,"[54, 87, 91]"
AWAY_TEAM_NAME,object,0,35,"[SpVgg Greuther Fürth, Eintracht Frankfurt, He..."
AWAY_TEAM,object,34,35,"[Bayern, Leverkusen, nan]"
AWAY_ICON,object,0,37,[https://upload.wikimedia.org/wikipedia/common...
GOALS_HOME,int64,0,10,"[1, 4, 2]"
GOALS_AWAY,int64,0,9,"[3, 3, 0]"
DRAW,float64,0,2,"[1.0, 0.0, 0.0]"
WIN_HOME,float64,0,2,"[1.0, 0.0, 0.0]"
WIN_AWAY,float64,0,2,"[0.0, 0.0, 1.0]"

In [28]:
df.columns

Index(['Unnamed: 0', 'MATCH_DATE', 'LEAGUE_NAME', 'SEASON', 'LEAGUE',
       'FINISHED', 'LOCATION', 'VIEWER', 'MATCHDAY', 'MATCHDAY_NR',
       'HOME_TEAM_ID', 'HOME_TEAM_NAME', 'HOME_TEAM', 'HOME_ICON',
       'AWAY_TEAM_ID', 'AWAY_TEAM_NAME', 'AWAY_TEAM', 'AWAY_ICON',
       'GOALS_HOME', 'GOALS_AWAY', 'DRAW', 'WIN_HOME', 'WIN_AWAY'],
      dtype='object')

In [32]:
# df = df.drop(columns='Unnamed: 0')

display(df.loc[:,['HOME_TEAM_ID', 'HOME_TEAM_NAME', 'HOME_TEAM', 'HOME_ICON',
       'AWAY_TEAM_ID', 'AWAY_TEAM_NAME', 'AWAY_TEAM', 'AWAY_ICON']])

,HOME_TEAM_ID,HOME_TEAM_NAME,HOME_TEAM,HOME_ICON,AWAY_TEAM_ID,AWAY_TEAM_NAME,AWAY_TEAM,AWAY_ICON
0,40,FC Bayern München,Bayern,https://i.imgur.com/jJEsJrj.png,87,Borussia Mönchengladbach,Gladbach,https://i.imgur.com/KSIk0Eu.png
1,65,1. FC Köln,Köln,https://upload.wikimedia.org/wikipedia/en/thum...,81,1. FSV Mainz 05,Mainz,https://upload.wikimedia.org/wikipedia/commons...
2,107,MSV Duisburg,Duisburg,https://upload.wikimedia.org/wikipedia/en/c/c8...,16,VfB Stuttgart,Stuttgart,https://i.imgur.com/v0tkpNx.png
3,100,Hamburger SV,HSV,https://upload.wikimedia.org/wikipedia/commons...,79,1. FC Nürnberg,Nürnberg,https://upload.wikimedia.org/wikipedia/commons...
4,131,VfL Wolfsburg,Wolfsburg,https://i.imgur.com/ucqKV4B.png,7,Borussia Dortmund,BVB,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...,...,...
5503,65,1. FC Köln,Köln,https://upload.wikimedia.org/wikipedia/en/thum...,40,FC Bayern München,Bayern,https://i.imgur.com/jJEsJrj.png
5504,1635,RB Leipzig,Leipzig,https://i.imgur.com/Rpwsjz1.png,9,FC Schalke 04,Schalke,https://upload.wikimedia.org/wikipedia/commons...
5505,16,VfB Stuttgart,Stuttgart,https://i.imgur.com/v0tkpNx.png,175,TSG 1899 Hoffenheim,Hoffenheim,https://i.imgur.com/gF0PfEl.png
5506,80,1. FC Union Berlin,Union Berlin,https://assets.dfb.de/uploads/000/018/232/smal...,134,Werder Bremen,Bremen,https://upload.wikimedia.org/wikipedia/commons...
5507,131,VfL Wolfsburg,Wolfsburg,https://i.imgur.com/ucqKV4B.png,54,Hertha BSC,Hertha,https://i.imgur.com/apFwbYZ.png

In [41]:
df = df.loc[:,['MATCH_DATE', 'SEASON','LOCATION','MATCHDAY_NR','HOME_TEAM_NAME','AWAY_TEAM_NAME','GOALS_HOME', 'GOALS_AWAY', 'DRAW', 'WIN_HOME', 'WIN_AWAY']]
type(df)

display(df.loc[:,'SEASON'].nunique())
display(df.loc[:,'SEASON'].unique())

18

array([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [42]:
display(
    "Shape",
    df.shape,
    "Description",
    df.describe().round(2).T,
    "Duplicates",
    df.duplicated().sum(),
)


pd.DataFrame(
    {
        "Data Types": df.dtypes,
        "Missing Values": df.isnull().sum(),
        "Unique Values": df.nunique(),
        "Sample Values": [df[col].sample(3).tolist() for col in df.columns]
    })

'Shape'

(5508, 11)

'Description'

              count     mean   std     min     25%     50%     75%     max
SEASON       5508.0  2013.50  5.19  2005.0  2009.0  2013.5  2018.0  2022.0
MATCHDAY_NR  5508.0    17.50  9.81     1.0     9.0    17.5    26.0    34.0
GOALS_HOME   5508.0     1.39  1.30     0.0     0.0     1.0     2.0     9.0
GOALS_AWAY   5508.0     1.08  1.13     0.0     0.0     1.0     2.0     8.0
DRAW         5508.0     0.29  0.45     0.0     0.0     0.0     1.0     1.0
WIN_HOME     5508.0     0.43  0.49     0.0     0.0     0.0     1.0     1.0
WIN_AWAY     5508.0     0.28  0.45     0.0     0.0     0.0     1.0     1.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
MATCH_DATE,object,0,2603,"[2017-01-28 18:30:00, 2017-09-19 18:30:00, 200..."
SEASON,int64,0,18,"[2019, 2016, 2007]"
LOCATION,object,0,33,"[Leipzig, Hamburg, Frankfurt]"
MATCHDAY_NR,int64,0,34,"[31, 5, 1]"
HOME_TEAM_NAME,object,0,35,"[Bayer Leverkusen, VfL Wolfsburg, Bayer Leverk..."
AWAY_TEAM_NAME,object,0,35,"[1. FC Nürnberg, SC Freiburg, Borussia Mönchen..."
GOALS_HOME,int64,0,10,"[2, 1, 2]"
GOALS_AWAY,int64,0,9,"[1, 1, 2]"
DRAW,float64,0,2,"[0.0, 0.0, 1.0]"
WIN_HOME,float64,0,2,"[0.0, 0.0, 0.0]"
WIN_AWAY,float64,0,2,"[1.0, 0.0, 1.0]"

In [ ]:
df.loc[:,'DRAW'] = df.loc[:,'DRAW'].astype('int')
df.loc[:,'WIN_HOME'] = df.loc[:,'WIN_HOME'].astype('int')
df.loc[:,'WIN_AWAY'] = df.loc[:,'WIN_AWAY'].astype('int')

# maybe cast as categories later

In [ ]:
# make sure team names are consistent

# get list of unique home teams

home_teams = df['HOME_TEAM_NAME'].unique().tolist()
home_teams = sorted(home_teams)
away_teams = df['AWAY_TEAM_NAME'].unique().tolist()
away_teams = sorted(away_teams)

home_teams == away_teams

True

In [63]:
# change season 

season_list = sorted(df['SEASON'].unique().tolist())
season_list

correct_season = ['05_06', '06_07', '07_08', '08_09', '09_10', '10_11', '11_12',
                  '12_13', '13_14', '14_15', '15_16', '16_17', '17_18', '18_19',
                   '19_20', '20_21', '21_22', '22_23']

season_map = dict(zip(season_list, correct_season))
season_map

df['SEASON'] = df['SEASON'].replace(season_map)

df['SEASON'].unique()

array(['05_06', '06_07', '07_08', '08_09', '09_10', '10_11', '11_12',
       '12_13', '13_14', '14_15', '15_16', '16_17', '17_18', '18_19',
       '19_20', '20_21', '21_22', '22_23'], dtype=object)

In [ ]:
# get final rankings

In [ ]:

fig, ax = plt.subplots(figsize=(12, 10), dpi=200)

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", center=0, ax=ax);