# strength index via Elo

In [21]:
import os
import pandas as pd
import numpy as np

In [22]:
processed_path = os.path.join('c:\\Users\\Trainee.LAPTOP-7OL45FO7\\Desktop\\portfolio_projekt\\template_dsc', 'data', 'processed')

if os.path.exists(processed_path):
    print('True')


# get data
df_final_rankings = pd.read_csv(os.path.join(processed_path, 'Bundesliga_Rankings.csv'))
df_matches = pd.read_csv(os.path.join(processed_path, 'Bundesliga_Matches.csv'))

display(df_final_rankings.head())
display(df_matches.head())

True

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
0,1. Bundesliga,04_05,FC Bayern München,Bayern,34,77,24,5,5,75,33,42,1,100.000000
1,1. Bundesliga,04_05,FC Schalke 04,Schalke,34,63,20,11,3,56,46,10,2,94.176471
2,1. Bundesliga,04_05,Werder Bremen,Bremen,34,59,18,11,5,68,37,31,3,88.352941
3,1. Bundesliga,04_05,Hertha BSC,Hertha,34,58,15,6,13,59,31,28,4,82.529412
4,1. Bundesliga,04_05,VfB Stuttgart,Stuttgart,34,58,17,10,7,54,40,14,5,76.705882

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
0,2005-08-05 20:30:00,05_06,München,1,FC Bayern München,Borussia Mönchengladbach,3,0,0.0,1.0,0.0
1,2005-08-06 15:30:00,05_06,Köln,1,1. FC Köln,1. FSV Mainz 05,1,0,0.0,1.0,0.0
2,2005-08-06 15:30:00,05_06,Duisburg,1,MSV Duisburg,VfB Stuttgart,1,1,1.0,0.0,0.0
3,2005-08-06 15:30:00,05_06,Hamburg,1,Hamburger SV,1. FC Nürnberg,3,0,0.0,1.0,0.0
4,2005-08-06 15:30:00,05_06,Wolfsburg,1,VfL Wolfsburg,Borussia Dortmund,2,2,1.0,0.0,0.0

In [23]:
# focus on 5 comparable seasons: 09_10 to 14_15

df_rankings_5 = df_final_rankings.copy()
df_matches_5 = df_matches.copy()
dfs = [df_rankings_5, df_matches_5]

for df in dfs: 
    df = df[(df['SEASON'] == '09_10') | (df['SEASON'] == '10_11') | (df['SEASON'] == '11_12') | (df['SEASON'] == '12_13') | (df['SEASON'] == '13_14') | (df['SEASON'] == '14_15')]
    display(df.head())
    display(df.tail())

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
90,1. Bundesliga,09_10,FC Bayern München,Bayern,34,70,20,4,10,72,31,41,1,100.000000
91,1. Bundesliga,09_10,FC Schalke 04,Schalke,34,65,19,7,8,53,31,22,2,94.176471
92,1. Bundesliga,09_10,Werder Bremen,Bremen,34,61,17,7,10,71,40,31,3,88.352941
93,1. Bundesliga,09_10,Bayer Leverkusen,Leverkusen,34,59,15,5,14,65,38,27,4,82.529412
94,1. Bundesliga,09_10,Borussia Dortmund,Dortmund,34,57,16,9,9,54,42,12,5,76.705882

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
193,1. Bundesliga,14_15,VfB Stuttgart,Stuttgart,34,36,9,16,9,42,60,-18,14,24.294118
194,1. Bundesliga,14_15,Hertha BSC,Hertha,34,35,9,17,8,36,52,-16,15,18.470588
195,1. Bundesliga,14_15,Hamburger SV,HSV,34,35,9,17,8,25,50,-25,16,12.647059
196,1. Bundesliga,14_15,SC Freiburg,Freiburg,34,34,7,14,13,36,47,-11,17,6.823529
197,1. Bundesliga,14_15,SC Paderborn 07,Paderborn,34,31,7,17,10,31,65,-34,18,1.000000

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
1224,2009-08-07 20:30:00,09_10,Wolfsburg,1,VfL Wolfsburg,VfB Stuttgart,2,0,0.0,1.0,0.0
1225,2009-08-08 15:30:00,09_10,Dortmund,1,Borussia Dortmund,1. FC Köln,1,0,0.0,1.0,0.0
1226,2009-08-08 15:30:00,09_10,Nürnberg,1,1. FC Nürnberg,FC Schalke 04,1,2,0.0,0.0,1.0
1227,2009-08-08 15:30:00,09_10,Bremen,1,Werder Bremen,Eintracht Frankfurt,2,3,0.0,0.0,1.0
1228,2009-08-08 15:30:00,09_10,Berlin,1,Hertha BSC,Hannover 96,1,0,0.0,1.0,0.0

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
3055,2015-05-23 15:30:00,14_15,Hannover,34,Hannover 96,SC Freiburg,2,1,0.0,1.0,0.0
3056,2015-05-23 15:30:00,14_15,Frankfurt,34,Eintracht Frankfurt,Bayer Leverkusen,2,1,0.0,1.0,0.0
3057,2015-05-23 15:30:00,14_15,Hamburg,34,Hamburger SV,FC Schalke 04,2,0,0.0,1.0,0.0
3058,2015-05-23 15:30:00,14_15,Köln,34,1. FC Köln,VfL Wolfsburg,2,2,1.0,0.0,0.0
3059,2015-05-23 15:30:00,14_15,Paderborn,34,SC Paderborn 07,VfB Stuttgart,1,2,0.0,0.0,1.0

In [24]:
# Elo ---- pseudo code

# expected score 

expect_a = 1 /(1 + 10**np.exp(-(rating_a - rating_b)/c)) # c is hyperparameter: 
                                                    # how important are rating differences
expect_b = 1- expect_a

c = 20 # for now

# victory, loss, draw 

win_draw_loss_a = 1 # if victory
win_draw_loss_a = 0.5 # if draw
win_draw_loss_a = 0 # if loss

k= update_strength


rating_a_update = rating_a + k*(win_draw_loss_a - expect_a) # wenn A Favorit (expect_a > 0.5, aber w_d_l = 0.5 dann ist Unentschieden schlecht für das Rating von A)
rating_b_update = rating_b + k*(win_draw_loss_b - expect_b)

# add goal margin
m = margin_factor # important: not applicable if draw, as otherwise m=0, see below

if win_draw_loss == 0.5:
    m=1 # equations below become equations above
    rating_a_update = rating_a + k*m*(win_draw_loss_a - expect_a) # wenn A Favorit (expect_a > 0.5, aber w_d_l = 0.5 dann ist Unentschieden schlecht für das Rating von A)
    rating_b_update = rating_b + k*m*(win_draw_loss_b - expect_b)
else:
    m = 1 + alpha*(goal_difference) # alpha = 0.25 to start with

return rating_a_update, rating_b_update

NameError: name 'rating_a' is not defined

In [25]:
# clean function within class for Elo Update

import numpy as np



class TeamStrength:
    '''
    Class for rating updates on team strength within a league via different metrics, such as Elo, Poisson and Dixon Cole
    between two teams, team A (home) and team B (away).
    '''


    def __init__(self, rating_a, rating_b, goals_a, goals_b):
        # ratings before the match
        self.rating_a = rating_a
        self.rating_b = rating_b

        # scored goals
        self.goals_a = goals_a
        self.goals_b = goals_b

    @property
    def goal_difference(self):
        '''
        Absolute goal difference of the match between team A and team B
        '''
        return np.abs(self.goals_a - self.goals_b)
    
    @property
    def score_a(self):
        if self.goals_a > self.goals_b:
            return 1.0
        elif self.goals_a < self.goals_b:
            return 0.0
        return 0.5
    
    @property
    def score_b(self):
        return 1- self.score_a


    def elo_update(self, k=10, c=20, alpha=0.25):
        '''
        Update Elo ratings after each match
        '''

        # expected score 
        expect_a = 1 /(1 + 10 ** (-(self.rating_a - self.rating_b)/c))  
                                                            
        expect_b = 1- expect_a

        # add goals
        goal_margin_factor =  1 + alpha * self.goal_difference

        # rating changes
        delta_a = k * goal_margin_factor * (self.score_a - expect_a)
        delta_b = k * goal_margin_factor * (self.score_b - expect_b)

        # updated ratings
        new_rating_a = self.rating_a + delta_a
        new_rating_b = self.rating_b + delta_b

        return {
        "expect_a": expect_a,
        "expect_b": expect_b,
        "score_a": self.score_a,
        "score_b": self.score_b,
        "goal_margin_factor": goal_margin_factor,
        "delta_a": delta_a,
        "delta_b": delta_b,
        "new_rating_a": new_rating_a,
        "new_rating_b": new_rating_b,
        }

In [26]:
## sanity check elo. clear win, draw and clear loss. First vs Third

match_win_home = TeamStrength(rating_a=100, rating_b=88.353, goals_a=3, goals_b=0)
match_draw = TeamStrength(rating_a=100, rating_b=88.353, goals_a=2, goals_b=2)
match_loss_home = TeamStrength(rating_a=100, rating_b=88.353, goals_a=0, goals_b=3)

result_win_home = match_win_home.elo_update(k=10, c=20, alpha=0.25)
result_draw = match_draw.elo_update(k=10, c=20, alpha=0.25)
result_loss_home = match_loss_home.elo_update(k=10, c=20, alpha=0.25)

print(result_win_home)
print(result_draw)
print(result_loss_home)

# take home message: works. 
# maybe investigate asymetric loss, i.e. the score the winner's rating wins is not identical to the score the loser's rating loses

{'expect_a': 0.7926396212719551, 'expect_b': 0.20736037872804491, 'score_a': 1.0, 'score_b': 0.0, 'goal_margin_factor': np.float64(1.75), 'delta_a': np.float64(3.628806627740786), 'delta_b': np.float64(-3.628806627740786), 'new_rating_a': np.float64(103.62880662774079), 'new_rating_b': np.float64(84.72419337225921)}
{'expect_a': 0.7926396212719551, 'expect_b': 0.20736037872804491, 'score_a': 0.5, 'score_b': 0.5, 'goal_margin_factor': np.float64(1.0), 'delta_a': np.float64(-2.926396212719551), 'delta_b': np.float64(2.926396212719551), 'new_rating_a': np.float64(97.07360378728045), 'new_rating_b': np.float64(91.27939621271955)}
{'expect_a': 0.7926396212719551, 'expect_b': 0.20736037872804491, 'score_a': 0.0, 'score_b': 1.0, 'goal_margin_factor': np.float64(1.75), 'delta_a': np.float64(-13.871193372259214), 'delta_b': np.float64(13.871193372259214), 'new_rating_a': np.float64(86.12880662774079), 'new_rating_b': np.float64(102.22419337225921)}

In [33]:
# Elo for a season or more than one season

class TeamStrengthSeason:
    '''
    Estimating the strength of a team during a whole season from match data.

    Current implementation: 
        - Elo (strength indices for teams)
    
    Planned implementations:
        - Poisson / Dixon-Coles (defensive and offensive strength as additional features)

    '''

    def __init__(self, df_matches, df_rankings, seasons):
        '''
        Extract seasons to investigate from match and rankings data.
        '''

        self.df_matches = df_matches.copy()
        self.df_rankings = df_rankings.copy()
        self.seasons  = seasons

        # keep only requested seasons
        self.df_matches = self.df_matches[self.df_matches['SEASON'].isin(seasons)].copy()
        self.df_rankings = self.df_rankings[self.df_rankings['SEASON'].isin(seasons)].copy()

    @staticmethod
    def _elo_expected_score(rating_home, rating_away, c=20):
        '''
        Expected Elo score for home team
        '''

        return 1 / (1 + 10 ** (-(rating_home - rating_away) / c))
    
    @staticmethod
    def _actual_score(goals_home, goals_away):
        """
        Actual Elo score for the home team.
        """
        if goals_home > goals_away:
            return 1.0
        elif goals_home < goals_away:
            return 0.0
        return 0.5

    @staticmethod
    def _goal_margin_factor(goals_home, goals_away, alpha=0.25):
        """
        Goal-margin factor for Elo updates.
        """
        goal_difference = abs(goals_home - goals_away)
        return 1 + alpha * goal_difference

    def fit_elo(self, k=10, c=20, alpha=0.25):
        """
        Run sequential Elo updates through all selected seasons.

        Parameters
        ----------
        k : float
            Base Elo update size.
        c : float
            Elo scale hyperparameter.
        alpha : float
            Goal difference weight.

        Returns
        -------
        match_history : pd.DataFrame
            Match-by-match Elo history.
        final_ratings : pd.DataFrame
            Final Elo rating per team and season.
        """

        all_match_rows = [] # collect all match per match results
        all_final_rows = [] # collect final ratings per team per season

        # run season individually, start for all seasons from same initial rating for first, second, third, ... 18th
        for season in self.seasons:
            # season match data in chronological order
            season_matches = (
                self.df_matches[self.df_matches['SEASON'] == season]    # get all matches of a particular season
                .sort_values(by='MATCHDAY_NR')                          # sort them according to match day
                .reset_index(drop=True)                                 # reset index after sorting
            )

            # final rankings / initial ratings for this very season
            season_rankings = self.df_rankings[self.df_rankings['SEASON'] == season].copy()

            # initialize ratings from ranking file
            ratings = dict(zip(season_rankings['Team'], season_rankings['Ratings_initial']))

            # iterate through all matches
            for _, row in season_matches.iterrows():  
                home_team = row['HOME_TEAM_NAME']
                away_team = row['AWAY_TEAM_NAME']
                goals_home = int(row['GOALS_HOME'])
                goals_away = int(row['GOALS_AWAY'])

                rating_home_before = float(ratings[home_team])
                rating_away_before = float(ratings[away_team])

                # expected score
                expect_home = self._elo_expected_score(rating_home_before, rating_away_before, c=c)
                expect_away = 1 - expect_home

                # actual score
                score_home = self._actual_score(goals_home, goals_away)
                score_away = 1 - score_home

                # goal-margin factor
                goal_margin_factor = self._goal_margin_factor(goals_home, goals_away, alpha=alpha)

                # rating deltas
                delta_home = k * goal_margin_factor * (score_home - expect_home)
                delta_away = k * goal_margin_factor * (score_away - expect_away)

                # updated ratings
                rating_home_after = rating_home_before + delta_home
                rating_away_after = rating_away_before + delta_away

                # write back
                ratings[home_team] = rating_home_after
                ratings[away_team] = rating_away_after

                # store match history
                all_match_rows.append({
                    'SEASON': season,
                    'MATCH_DATE': row['MATCH_DATE'],
                    'MATCHDAY_NR': row['MATCHDAY_NR'],
                    'HOME_TEAM_NAME': home_team,
                    'AWAY_TEAM_NAME': away_team,
                    'GOALS_HOME': goals_home,
                    'GOALS_AWAY': goals_away,
                    'rating_home_before': rating_home_before,
                    'rating_away_before': rating_away_before,
                    'expect_home': expect_home,
                    'expect_away': expect_away,
                    'score_home': score_home,
                    'score_away': score_away,
                    'goal_margin_factor': goal_margin_factor,
                    'delta_home': delta_home,
                    'delta_away': delta_away,
                    'rating_home_after': rating_home_after,
                    'rating_away_after': rating_away_after
                })

            # store final ratings of season
            for team, final_rating in ratings.items():
                all_final_rows.append({
                    'SEASON': season,
                    'Team': team,
                    'Elo_final': final_rating
                })

        match_history = pd.DataFrame(all_match_rows)

        final_ratings = (
            pd.DataFrame(all_final_rows)
            .sort_values(by=['SEASON', 'Elo_final'], ascending=[True, False])
            .reset_index(drop=True)
        )

        return match_history, final_ratings

In [30]:
type(df_final_rankings)

pandas.core.frame.DataFrame

In [34]:
# check seasons
seasons = ['09_10', '10_11', '11_12', '12_13', '13_14', '14_15']

# generate model
model = TeamStrengthSeason(df_matches, df_final_rankings, seasons)

# fit elo
match_history, final_ratings = model.fit_elo(k=10, c=20, alpha=0.25)

# display results
final_ratings.head(20)

   SEASON                      Team  Elo_final
0   09_10             Werder Bremen  70.000018
1   09_10             VfB Stuttgart  66.058128
2   09_10         FC Bayern München  66.026114
3   09_10               SC Freiburg  60.491774
4   09_10       TSG 1899 Hoffenheim  58.749114
5   09_10             FC Schalke 04  57.745454
6   09_10           1. FSV Mainz 05  56.586818
7   09_10               Hannover 96  56.258619
8   09_10             VfL Wolfsburg  53.264676
9   09_10          Bayer Leverkusen  48.970748
10  09_10                Hertha BSC  48.138361
11  09_10              Hamburger SV  46.841560
12  09_10         Borussia Dortmund  45.511782
13  09_10                1. FC Köln  38.754996
14  09_10       Eintracht Frankfurt  37.602022
15  09_10  Borussia Mönchengladbach  35.962970
16  09_10            1. FC Nürnberg  33.507201
17  09_10                VfL Bochum  28.529645
18  10_11         FC Bayern München  74.837278
19  10_11      1. FC Kaiserslautern  69.019052

In [38]:
final_ratings.head(54)

   SEASON                      Team  Elo_final
0   09_10             Werder Bremen  70.000018
1   09_10             VfB Stuttgart  66.058128
2   09_10         FC Bayern München  66.026114
3   09_10               SC Freiburg  60.491774
4   09_10       TSG 1899 Hoffenheim  58.749114
5   09_10             FC Schalke 04  57.745454
6   09_10           1. FSV Mainz 05  56.586818
7   09_10               Hannover 96  56.258619
8   09_10             VfL Wolfsburg  53.264676
9   09_10          Bayer Leverkusen  48.970748
10  09_10                Hertha BSC  48.138361
11  09_10              Hamburger SV  46.841560
12  09_10         Borussia Dortmund  45.511782
13  09_10                1. FC Köln  38.754996
14  09_10       Eintracht Frankfurt  37.602022
15  09_10  Borussia Mönchengladbach  35.962970
16  09_10            1. FC Nürnberg  33.507201
17  09_10                VfL Bochum  28.529645
18  10_11         FC Bayern München  74.837278
19  10_11      1. FC Kaiserslautern  69.019052
20  10_11           1. FSV Mainz 05  61.609364
21  10_11  Borussia Mönchengladbach  61.537622
22  10_11             VfB Stuttgart  61.239990
23  10_11             VfL Wolfsburg  57.515181
24  10_11             Werder Bremen  55.600143
25  10_11               Hannover 96  53.216179
26  10_11                1. FC Köln  53.002556
27  10_11         Borussia Dortmund  52.579859
28  10_11          Bayer Leverkusen  48.677957
29  10_11       TSG 1899 Hoffenheim  42.300091
30  10_11              Hamburger SV  41.687596
31  10_11             FC Schalke 04  38.693517
32  10_11               SC Freiburg  38.248311
33  10_11            1. FC Nürnberg  36.360683
34  10_11              FC St. Pauli  31.455622
35  10_11       Eintracht Frankfurt  31.419001
36  11_12         Borussia Dortmund  82.122978
37  11_12         FC Bayern München  72.537774
38  11_12          Bayer Leverkusen  68.575248
39  11_12             VfB Stuttgart  61.479815
40  11_12  Borussia Mönchengladbach  58.746203
41  11_12               FC Augsburg  58.353629
42  11_12               SC Freiburg  54.627008
43  11_12             FC Schalke 04  54.124980
44  11_12            1. FC Nürnberg  51.114840
45  11_12               Hannover 96  47.664064
46  11_12             VfL Wolfsburg  46.494552
47  11_12              Hamburger SV  45.721154
48  11_12           1. FSV Mainz 05  41.319032
49  11_12                Hertha BSC  40.895000
50  11_12             Werder Bremen  32.217378
51  11_12      1. FC Kaiserslautern  31.381237
52  11_12       TSG 1899 Hoffenheim  31.149784
53  11_12                1. FC Köln  30.475323